name: Resume ci Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{github.run_number}}
    - name: Build latest . --file Dockerfile --tag my-image-name
      run: docker login -u ${{secrets.Registry_Username}} -p ${{secrets.Registry_pass}}
    - name: tag image 
      run: docker tag my-image-name:${{github.run_number}} ${{secrets.Registry_Username}}/my-image:${{github/run_number}}
  
